import type { Ticket } from '../domain/ticket'

export const seedTickets: Ticket[] = [
  {
    id: 'IT-001',
    ticketNumber: 'IT-001',
    customer: 'Veganic Nail Spa',
    title: 'Clover không thể kết nối với Nail360',
    description: 'Khách hàng báo thiết bị Clover không thể kết nối với Nail360.',
    category: 'Clover / Payment',
    priority: 'High',
    status: 'Resolved',
    investigation: 'Kết nối Internet vẫn hoạt động, thiết bị Clover đang trực tuyến. Đã kiểm tra cấu hình Clover của cửa hàng.',
    rootCause: 'Clover Environment đang được đặt ở chế độ Sandbox.',
    solution: 'Đã đổi Clover Environment từ Sandbox sang Production.',
    internalNotes: 'Nếu gặp lỗi tương tự ở tiệm đang hoạt động, hãy kiểm tra Clover Environment trước.',
    createdAt: '2026-09-24T10:30:00.000Z',
    updatedAt: '2026-09-24T11:05:00.000Z',
  },
  {
    id: 'IT-002',
    ticketNumber: 'IT-002',
    customer: 'Lotus Nail Lounge',
    title: 'Máy in hóa đơn quầy lễ tân thường xuyên mất kết nối',
    description: 'Máy in hóa đơn bị ngắt kết nối khỏi máy tính quầy lễ tân vài lần trong ngày.',
    category: 'Printer / Hardware',
    priority: 'Medium',
    status: 'Investigating',
    investigation: 'Đã xác nhận máy in có nguồn và in được trang kiểm tra. Cáp USB có vẻ lỏng khi di chuyển máy tính.',
    rootCause: '',
    solution: '',
    internalNotes: 'Chuẩn bị cáp USB thay thế cho lần hỗ trợ tiếp theo.',
    createdAt: '2026-09-24T14:15:00.000Z',
    updatedAt: '2026-09-25T08:40:00.000Z',
  },
  {
    id: 'IT-003',
    ticketNumber: 'IT-003',
    customer: 'Gloss House Studio',
    title: 'Khách không nhận được tin nhắn nhắc lịch hẹn',
    description: 'Nhân viên báo một số khách không nhận được tin nhắn nhắc lịch hẹn trong tuần này.',
    category: 'Appointment / Booking',
    priority: 'High',
    status: 'Waiting',
    investigation: 'Đã kiểm tra cài đặt nhắc lịch và xác nhận tác vụ gửi nhắc lịch đang chạy. Hồ sơ khách bị ảnh hưởng đều có số điện thoại.',
    rootCause: '',
    solution: '',
    internalNotes: 'Đang chờ hai khách bị ảnh hưởng xác nhận nhà mạng và kiểm tra tin nhắn có bị lọc hay không.',
    createdAt: '2026-09-25T07:20:00.000Z',
    updatedAt: '2026-09-25T08:10:00.000Z',
  },
  {
    id: 'IT-004',
    ticketNumber: 'IT-004',
    customer: 'Atelier Nail Bar',
    title: 'Quản lý không thể đặt lại mật khẩu tài khoản',
    description: 'Quản lý nhận được thông báo liên kết hết hạn khi mở email đặt lại mật khẩu.',
    category: 'Account / Login',
    priority: 'Low',
    status: 'New',
    investigation: '',
    rootCause: '',
    solution: '',
    internalNotes: '',
    createdAt: '2026-09-25T09:05:00.000Z',
    updatedAt: '2026-09-25T09:05:00.000Z',
  },
  {
    id: 'IT-005',
    ticketNumber: 'IT-005',
    customer: 'Pearl Nail Bar',
    title: 'Tổng doanh thu cuối ngày không khớp với Clover',
    description: 'Báo cáo doanh thu cuối ngày thiếu một giao dịch thẻ so với tổng kết lô trên Clover.',
    category: 'Report',
    priority: 'Critical',
    status: 'Closed',
    investigation: 'Đã so sánh file báo cáo với lô giao dịch trên Clover. Một giao dịch được ghi nhận ngay sau thời điểm chốt ngày tại tiệm.',
    rootCause: 'Báo cáo dùng mốc nửa đêm UTC thay vì múi giờ của tiệm để xác định ngày kinh doanh.',
    solution: 'Đã điều chỉnh khoảng ngày theo múi giờ của tiệm và xác nhận tổng số liệu đã khớp.',
    internalNotes: 'Kiểm tra múi giờ của cửa hàng khi đối soát doanh thu cuối ngày.',
    createdAt: '2026-09-23T15:45:00.000Z',
    updatedAt: '2026-09-24T09:30:00.000Z',
  },
]
